// carta.js — Contenido de la carta virtual (fuente: andirestaurante.com.ar/nuestra-carta/)
// Precios y platos se actualizan manualmente según la carta del sitio.

export const CARTA_HEADER = [
  { icon: 'CupSoda', text: 'Servicio de mesa por persona $3.500' },
  { icon: 'ShoppingBag', text: 'Delivery & Take Away 10% OFF' },
  { icon: 'Wifi', text: 'WIFI: Andi Acerca / Pass: andi1970' },
];

export const SUGERENCIAS = [
  { name: 'Agnolitis de Portobelo con salsa de hongo, manteca de salvia y cabutia asada', price: 26000 },
  { name: 'San Pedro de Yacochuya by Michel Rolland', price: 28000 },
  { name: 'Volcán de Ñoquis o Tallarines en hogaza de masa madre', price: 25500 },
  { name: 'Asado de tira banderita (con dip de criolla)', price: 26000 },
  { name: 'Budweiser 710', price: 7500 },
  { name: 'Frutillas con crema', price: 10500 },
  { name: 'Osobuco braseado', price: 32500 },
  { name: 'Gin Tonic (DIODIN premium)', price: 9000 },
];

export const CARTA = [
  {
    title: 'Bebidas',
    icon: 'Wine',
    groups: [
      {
        title: 'Sin alcohol',
        items: [
          { name: 'Agua mineral 750cc', price: 4500 },
          { name: 'Agua mineral 500cc', price: 3500 },
          { name: 'Exprimido de naranja', price: 6500 },
          { name: 'Corte de limón', price: 1500 },
          { name: 'Limonada / Pomelada 1 lts', price: 8000 },
          { name: 'Gaseosa 1.5L', price: 8000 },
          { name: 'Gaseosa 500cc', price: 4000 },
        ],
      },
      {
        title: 'Vinos tintos',
        items: [
          { name: 'Angelica Zapata Malbec', price: 42000 },
          { name: 'El Enemigo Malbec', price: 34000 },
          { name: 'Salentein Numina 3/4', price: 20000 },
          { name: 'Salentein Reserva Malbec 3/4', price: 16000 },
          { name: 'Alfredo Roca "Fincas"', price: 15000 },
          { name: 'Alfredo Roca Blend Alma Inquieta', price: 17000 },
          { name: 'Saint Felicien Malbec', price: 15000 },
          { name: 'Cordero con piel de Lobo', price: 8000 },
          { name: 'Las Perdices Malbec', price: 16000 },
          { name: 'Nicasia Malbec Vineyards', price: 12500 },
          { name: 'Trumpeter', price: 12000 },
          { name: 'Laureano Gomez Malbec Reserva', price: 32000 },
          { name: 'Laureano Gomez Blend Reserva', price: 32000 },
          { name: 'Clos de los Siete Malbec', price: 22000 },
          { name: 'Petit Fleur Malbec (Bodega Monteviejo)', price: 22000 },
          { name: 'Gran Tomero Malbec', price: 28000 },
          { name: 'Mariflor by Michel Rolland Pinot Noir', price: 29000 },
          { name: 'Mariflor Malbec by Michel Rolland', price: 24000 },
          { name: 'Las Perdices Reserva Malbec', price: 24000 },
          { name: 'Laureano Gomez Tetris Malbec o Merlot', price: 15000 },
          { name: 'Yacochuya by Michel Rolland', price: 75000, sugerido: true },
          { name: 'San Pedro de Yacochuya by Michel Rolland', price: 28000, sugerido: true },
          { name: 'Coquena Malbec', price: 9500 },
        ],
      },
      {
        title: 'Vinos blancos',
        items: [
          { name: 'Cafayate Torrontés', price: 6500 },
          { name: 'Trumpeter Chardonnay / Sauvignon Blanc', price: 12000 },
          { name: 'Coquena Torrontés', price: 9500 },
          { name: 'Cordero con piel de lobo blanco dulce', price: 8000 },
        ],
      },
      {
        title: 'Birra industrial',
        items: [
          { name: 'Stella Artois 1 LTS', price: 12000 },
          { name: 'Corona 710', price: 10000 },
          { name: 'Budweiser 710', price: 7500, sugerido: true },
          { name: 'Corona sin alcohol 330', price: 5000 },
        ],
      },
      {
        title: 'Tragos',
        items: [
          { name: 'Gin Tonic (DIODIN premium)', desc: 'Limón / Lima / Pepino / Naranja / Menta', price: 9000, sugerido: true },
          { name: 'Aperol', desc: 'Spritz / Tonic', price: 8000 },
          { name: 'Caipiriña / Caipiroska (elegimos SERNOVA)', desc: 'Clásica / Maracuyá / Frutos Rojos / Kiwi', price: 8000 },
          { name: 'Campari', desc: 'Naranja / Tónica / Pomelo', price: 8000 },
          { name: 'Daiquiri', desc: 'Ron Bacardí / Frutilla / Durazno', price: 8000 },
          { name: 'Fernet', desc: 'Branca + lata coca cola x 311', price: 9000 },
          { name: 'Gancia', price: 7000 },
          { name: 'Mojito', price: 8000 },
          { name: 'Manhattan', desc: 'Whisky bourbon o rye / Vermut rojo / Amargo de angostura', price: 9000 },
          { name: 'Negroni', desc: 'Gin Diodin / Vermut rojo / Campari', price: 9000 },
          { name: 'Tom Collins', desc: 'Gin Diodin / Jugo de limón / Almíbar / Soda', price: 9000 },
          { name: 'Cynar Julep', desc: 'Cynar / Pomelo / Menta', price: 9000 },
          { name: 'Old Fashioned', desc: 'Whisky bourbon / Azúcar / Amargo de angostura', price: 9000 },
          { name: 'Cuba Libre', desc: 'Ron / Coca Cola / Jugo de lima', price: 9000 },
          { name: 'Boulevardier', desc: 'Whisky bourbon / Vermut rojo / Campari', price: 9000 },
          { name: 'Ferroviario', desc: 'Fernet, vermuth, soda y limón', price: 8000 },
        ],
      },
      {
        title: 'Tragos de autor',
        items: [
          { name: 'Trago de autor #1', desc: 'CINLET (Vermut blanco, Pepino, Albahaca y Jengibre)', price: 9000 },
        ],
      },
      {
        title: 'Espumantes',
        items: [
          { name: 'Champagne Baron B', price: 55000 },
          { name: 'Champagne Salentein Extra Brut', price: 28000 },
          { name: 'Sidra', price: 18000 },
        ],
      },
      {
        title: 'Birra tirada',
        items: [
          { name: 'Cervezas artesanales', desc: 'Golden (IBU 17 ABV 4,8%) · Honey (IBU 12 ABV 6,2%) · Robust Porter (IBU 30 ABV 5,9%)', price: 5000 },
          { name: 'Cervezas lupuladas', desc: 'IPA Citra · Scottish ale · Session IPA · IPA West Coast', price: 5500 },
        ],
      },
    ],
  },
  {
    title: 'Tapeo',
    icon: 'UtensilsCrossed',
    items: [
      { name: 'Papas Pulled Pork', desc: 'Bondiola braseada desmenuzada y BBQ', price: 16500 },
      { name: 'Provoleta crocante', desc: 'Con especias y un toque de oliva', price: 17500, veggie: true },
      { name: 'Rabas', price: 23000 },
      { name: 'Rolls', desc: 'Muzzarella, Roquefort y Nuez', price: 16000, veggie: true },
      { name: 'Bastones de Muzzarella', price: 16500, veggie: true },
      { name: 'Chips de batata', price: 13000, veggie: true },
      { name: 'Croquetas de espinaca', price: 16500, veggie: true },
      { name: 'Langostinos rebozados', desc: 'Frescos y crocantes', price: 19000 },
      { name: 'Nuggets de Pollo', desc: 'Pollo en serio y rebozado con semillas', price: 18000 },
      { name: 'Pizzas', desc: 'Consultanos variedades disponibles', price: 22000 },
      { name: 'Papas con salsa', desc: 'Cheddar y panceta / 4 quesos / verdeo / champignon', price: 15500 },
    ],
  },
  {
    title: 'Sandwiches y Hamburguesas',
    icon: 'Sandwich',
    groups: [
      {
        title: 'Sandwiches',
        items: [
          { name: 'Sándwiche de entraña en pan de papa casero', desc: 'Entraña en cocción lenta / jamón cocido natural / queso tybo / huevo a la plancha / tomate / lechuga manteca / alioli opcional', price: 27000 },
          { name: 'Panini de vacío desmenuzado', desc: 'Vacío de ternera braseado a la cerveza negra, desmechado. Acompañan papas rústicas', price: 27000 },
        ],
      },
      {
        title: 'Hamburguesas',
        items: [
          { name: 'Hambur Doble o Nada', desc: 'Doble medallón de carne, guacamole, cebolla dorada, panceta ahumada, queso cheddar y rúcula', price: 22000 },
          { name: 'Hambur Francesa', desc: 'Queso azul, cebolla dorada, panceta crocante y suave mostaza', price: 18000 },
          { name: 'Hambur Fusión', desc: 'Cheddar, cebolla dorada y panceta crocante', price: 18000 },
          { name: 'Hambur Mariachi', desc: 'Queso, guacamole y salsa criolla', price: 18000 },
          { name: 'Hambur Pulledpork', desc: 'Bondiola en cocción lenta desmechada, cebolla dorada, huevo a la plancha y salsa de mostaza y miel', price: 18000 },
          { name: 'Hambur Vintage', desc: 'Jamón, queso, huevo a la plancha, lechuga, tomate y queso', price: 18000 },
          { name: 'Provoguesa', desc: 'Medallón de carne de ternera, provoleta dorada con oliva y guacamole', price: 22000 },
        ],
      },
    ],
  },
  {
    title: 'Nuestras pastas',
    icon: 'Croissant',
    items: [
      { name: 'Raviolones de masa de remolacha', desc: 'Relleno con bondiola de cerdo en lenta cocción y desmechada', price: 13000 },
      { name: 'Raviolones de masa de espinaca', desc: 'Relleno de osobuco braseado', price: 13000 },
      { name: 'Canelones', desc: 'Verdura y carne / ricota y espinaca', price: 11500 },
      { name: 'Lasagna', price: 12500 },
      { name: 'Ñoquis', desc: 'Papa / espinaca', price: 11500, veggie: true },
      { name: 'Panzottis', desc: 'Pollo y puerro', price: 12500 },
      { name: 'Panzottis Negros', desc: 'Calamar y hongos secos', price: 13500 },
      { name: 'Ravioles', desc: 'Verdura / Ricota / Verdura y carne', price: 12500 },
      { name: 'Sorrentinos', desc: 'Ricota y Jamón', price: 12500 },
      { name: 'Sorrentinos', desc: 'Calabaza y Muzzarella', price: 12500, veggie: true },
      { name: 'Sorrentinos de masa integral', desc: 'Calabaza, Roquefort y nuez', price: 12500, veggie: true },
      { name: 'Sorrentinos Verdes', desc: 'Rellenos de salmón rosado', price: 13500 },
      { name: 'Tagliatellis Negros', desc: 'En tinta de calamar', price: 12500 },
      { name: 'Tallarines', desc: 'Al huevo / espinaca y albahaca', price: 11500, veggie: true },
      { name: 'Volcán de Ñoquis o Tallarines en hogaza de masa madre', price: 25500, sugerido: true },
      { name: 'Cannoli relleno de ricota, hongos y panceta', price: 13500 },
      { name: 'Tortelloni del corazón', desc: 'Relleno de pollo, hongo, cebolla colorada y nueces', price: 12500 },
      { name: 'Agnolitis de Portobelo con salsa de hongo, manteca de salvia y cabutia asada', price: 26000, sugerido: true },
    ],
  },
  {
    title: 'Salsas',
    icon: 'Droplets',
    items: [
      { name: 'Salsa de salmón rosado a la crema', desc: 'Crema de leche, fondue de salmón rosado', price: 13500 },
      { name: 'Andi', desc: 'Salsa de tomate, crema de leche, morrones, jamón y gratinado de queso', price: 10000 },
      { name: '4 Quesos', desc: 'Crema de leche, queso roquefort, fontina, gruyere y cuartirolo', price: 10000 },
      { name: 'Bolognesa', desc: 'Salsa de tomate y carne picada', price: 10000 },
      { name: 'Boscaiola', desc: 'Panceta, champignones, crema de leche, cebolla de verdeo y perejil', price: 10000 },
      { name: 'Carbonara', desc: 'Salsa blanca, panceta y gratinado de provolone', price: 10000 },
      { name: 'Crema de Camarones', price: 13500 },
      { name: 'Crema de champignones', desc: 'Crema de leche y champignones', price: 10000 },
      { name: 'Florentina', desc: 'Espinaca y salsa blanca gratinada', price: 10000 },
      { name: 'Hongos', desc: 'Crema de leche, hongos secos, panceta y cebolla rehogada', price: 13500 },
      { name: 'Parisiene', desc: 'Salsa blanca, jamón, pollo y gratinado de queso', price: 10000 },
      { name: 'Pesto', desc: 'Albahaca fresca, ajo y nuez', price: 10000 },
      { name: 'Salsa de tomate', price: 8000 },
      { name: 'Salsa Rosa', price: 8000 },
      { name: 'Verdeo', desc: 'Crema de leche, cebolla de verdeo rehogada en manteca', price: 10000 },
    ],
  },
  {
    title: 'Carnes',
    icon: 'Drumstick',
    groups: [
      {
        title: 'Rojas',
        items: [
          { name: 'Bife de Chorizo a la parrilla', price: 25000 },
          { name: 'Medallón de Lomo a la parrilla', price: 26000 },
          { name: 'Bife de chorizo con salsas a elección', desc: 'Salsa a Champiñón, Verdeo, Roquefort, 4 quesos. Sale con papas crinkle!', price: 34500 },
          { name: 'Medallón de Lomo con salsas a elección', desc: 'Salsa de champiñón, Verdeo, Roquefort, 4 quesos. Sale con papas crinkle!', price: 36500 },
          { name: 'Milandi', desc: 'Milanesa de ternera, cheddar, panceta, verdeo y huevo a la plancha. Sale con papas rejilla!', price: 29000 },
          { name: 'Milanesa de Ternera', price: 17500 },
          { name: 'Napolitana de Ternera', price: 22500 },
          { name: 'Osobuco braseado', desc: 'Con puré de cabutia, zanahoria y jengibre', price: 32500, sugerido: true },
          { name: 'Milanesitas de peceto con tallarines de espinaca salteado en manteca de salvia y cherry', price: 25000 },
          { name: 'Asado de tira banderita (con dip de criolla)', price: 26000, sugerido: true },
        ],
      },
      {
        title: 'Cerdo',
        items: [
          { name: 'Bondiola Braseada', desc: 'Con salsa y guarnición a elección', price: 26000 },
          { name: 'Bondiola Braseada', price: 17500 },
          { name: 'Matambrito', price: 22000 },
          { name: 'Matambrito a la Pizza', desc: 'Con guarnición a elección', price: 28000 },
        ],
      },
      {
        title: 'Ave',
        items: [
          { name: 'Cuarto de pollo', price: 13500 },
          { name: 'Milanesa de Pollo', price: 14000 },
          { name: 'Napolitana de Pollo', price: 18500 },
          { name: 'Pollo deshuesado', desc: 'Con salsa a elección. Sale con papitas crinkle!', price: 25000 },
          { name: 'Supremas Varias', desc: 'Maryland / Churchill / San Antonio / Andi / Suiza. Sale con papas fritas!', price: 25000 },
          { name: 'Wok de Vegetales y Pollo', price: 25000 },
        ],
      },
      {
        title: 'Guarniciones',
        items: [
          { name: 'Chips de batata', price: 13000 },
          { name: 'Papas Fritas', price: 10000 },
          { name: 'Papas Rejilla', price: 10000 },
          { name: 'Puré', desc: 'Papa / calabaza / cabutia', price: 10000 },
          { name: 'Boniato frito', price: 11500, veggie: true },
        ],
      },
    ],
  },
  {
    title: 'Pesca',
    icon: 'Fish',
    items: [
      { name: 'Trucha al limón', price: 24500 },
      { name: 'Trucha con salsa y guarnición', price: 30000 },
      { name: 'Filette de abadejo', price: 20000 },
      { name: 'Filette de Merluza', desc: 'A la romana', price: 14000 },
      { name: 'Filette de Merluza', desc: 'Con salsa y guarnición a elección', price: 22000 },
      { name: 'Abadejo al Roquefort', desc: 'Con guarnición a elección', price: 29000 },
      { name: 'Salmón Rosado', desc: 'Con salsa de azafrán y timbal de arroz negro', price: 34500 },
      { name: 'Salmón Rosado', desc: 'Con wok de vegetales', price: 30000 },
      { name: 'Wok de langostinos', desc: 'Con pasta, vegetales y langostinos', price: 29000 },
    ],
  },
  {
    title: 'Ensaladas',
    icon: 'Salad',
    items: [
      { name: 'Armonía', desc: 'Mix de verdes, jamón crudo, aceitunas negras, tomates cherrys, queso, nueces y almendras', price: 16000 },
      { name: 'Ensalada a elección', desc: 'Consultanos opciones disponibles', price: 10000 },
      { name: 'Ensaladas Caesar', desc: 'Lechuga, croutons, fajitas de pollo, salsa caesar, láminas de queso y mix de semillas', price: 18000 },
      { name: 'Fresta', desc: 'Rúcula, palta, tomates cherry, salmón ahumado, choclo, huevo (opción veggie: queso por salmón)', price: 23000 },
    ],
  },
  {
    title: 'Postres',
    icon: 'IceCreamBowl',
    groups: [
      {
        title: 'Postres',
        items: [
          { name: 'Chocotorta Individual', price: 10000 },
          { name: 'Mousse de Chocolate Semiamargo y Blanco', price: 14000 },
          { name: 'Borrachito de Vainilla', price: 8500 },
          { name: 'Affogato', desc: 'Con helado de pistacho o crema americana', price: 10000 },
          { name: 'Postre Almendrado / Imperial / Nevado', price: 8500 },
          { name: 'Bombón Suizo / Escocés', price: 8500 },
          { name: 'Brownie', desc: 'Con helado y frutos rojos', price: 12000 },
          { name: 'Don Pedro', desc: 'Helado americana / crema / nueces / whiskey', price: 18000 },
          { name: 'Flan Casero', price: 9500 },
          { name: 'Frutillas con crema', price: 10500, sugerido: true },
          { name: 'Mousse de Chocolate', price: 10000 },
          { name: 'Panqueque de dulce de leche', price: 10000 },
          { name: 'Cheesecake de frutos rojos', price: 10000 },
          { name: 'Tiramisú', price: 10000 },
          { name: 'Volcán de Chocolate con bocha helado crema americana', price: 16500 },
          { name: 'Flan casero con dulce y/o crema', price: 11500 },
        ],
      },
      {
        title: 'Café',
        items: [
          { name: 'Café chico', price: 3000 },
          { name: 'Café jarrito', price: 4000 },
        ],
      },
    ],
  },
];